package org.jbiowhdesktop.component.panel.tabbedpanel;

import java.awt.Component;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.util.UUID;
import javax.swing.JTabbedPane;
import javax.swing.JTextField;
import org.jbiowhdesktop.component.icons.IconFetch;
import org.jbiowhdesktop.component.panel.AbstractDataSetView;
import org.jbiowhdesktop.component.panel.ConstrainPanel;
import org.jbiowhdesktop.component.panel.HomePanel;
import org.jbiowhdesktop.component.panel.SearchPanel;
import org.jbiowhdesktop.component.panel.list.AbstractListView;
import org.jbiowhdesktop.component.panel.sql.SQLBrowsePanel;
import org.jbiowhdesktop.component.panel.sql.SQLEditorPanel;

/**
 * This JPanel is the Close panel for JTabbedPanel
 *
 * $Author: r78v10a07@gmail.com $ $LastChangedDate: 2012-08-31 15:46:36 +0200
 * (Fri, 31 Aug 2012) $ $LastChangedRevision: 273 $
 *
 * @since Feb 10, 2012
 */
public class ClosePanel extends javax.swing.JPanel {

    /**
     * Creates new form ClosePanel
     */
    public ClosePanel(JTabbedPane jTabbedPane, String label, UUID uniqueKey, java.awt.event.ActionListener act) {
        initComponents();
        jLabel.setText(label);
        this.uniqueKey = uniqueKey;
        jBClose.setActionCommand(uniqueKey.toString());
        jBClose.addActionListener(act);
        this.jTabbedPane = jTabbedPane;
    }

    private void setBackLabel(Component toRemove, Component toAdd) {
        remove(toRemove);
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addComponent(toAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jBClose, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jBClose, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(toAdd));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBClose = new javax.swing.JButton();
        jLabel = new javax.swing.JLabel();

        jBClose.setFont(new java.awt.Font("Tahoma", 0, 5)); // NOI18N
        jBClose.setIcon(IconFetch.getInstance().getIcon(IconFetch.getInstance().CLOSE_ICON));

        jLabel.setText("a");
        jLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBClose, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBClose, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMouseClicked
        if (!evt.isConsumed() && evt.getClickCount() == 1) {
            for (int i = 0; i < jTabbedPane.getTabCount(); i++) {
                if (jTabbedPane.getComponentAt(i) instanceof SearchPanel) {
                    if (((SearchPanel) jTabbedPane.getComponentAt(i)).getUniqueKey().equals(uniqueKey)) {
                        jTabbedPane.setSelectedIndex(i);
                        break;
                    }
                } else if (jTabbedPane.getComponentAt(i) instanceof AbstractDataSetView) {
                    if (((AbstractDataSetView) jTabbedPane.getComponentAt(i)).getUniqueKey().equals(uniqueKey)) {
                        jTabbedPane.setSelectedIndex(i);
                        break;
                    }
                } else if (jTabbedPane.getComponentAt(i) instanceof ConstrainPanel) {
                    if (((ConstrainPanel) jTabbedPane.getComponentAt(i)).getUniqueKey().equals(uniqueKey)) {
                        jTabbedPane.setSelectedIndex(i);
                        break;
                    }
                } else if (jTabbedPane.getComponentAt(i) instanceof HomePanel) {
                    if (((HomePanel) jTabbedPane.getComponentAt(i)).getUniqueKey().equals(uniqueKey)) {
                        jTabbedPane.setSelectedIndex(i);
                        break;
                    }
                } else if (jTabbedPane.getComponentAt(i) instanceof SQLBrowsePanel) {
                    if (((SQLBrowsePanel) jTabbedPane.getComponentAt(i)).getUniqueKey().equals(uniqueKey)) {
                        jTabbedPane.setSelectedIndex(i);
                        break;
                    }
                } else if (jTabbedPane.getComponentAt(i) instanceof SQLEditorPanel) {
                    if (((SQLEditorPanel) jTabbedPane.getComponentAt(i)).getUniqueKey().equals(uniqueKey)) {
                        jTabbedPane.setSelectedIndex(i);
                        break;
                    }
                } else if (jTabbedPane.getComponentAt(i) instanceof AbstractListView) {
                    if (((AbstractListView) jTabbedPane.getComponentAt(i)).getUniqueKey().equals(uniqueKey)) {
                        jTabbedPane.setSelectedIndex(i);
                        break;
                    }
                }

            }
            evt.consume();
        } else if (!evt.isConsumed() && evt.getClickCount() == 2) {
            textfield = new JTextField(jLabel.getText(), jLabel.getText().length());
            textfield.setBackground(new java.awt.Color(238, 238, 238));
            textfield.addKeyListener(new KeyListener() {
                @Override
                public void keyTyped(KeyEvent e) {
                }

                @Override
                public void keyPressed(KeyEvent e) {
                }

                @Override
                public void keyReleased(KeyEvent e) {
                    if (e.getKeyCode() == KeyEvent.VK_ENTER && !textfield.getText().isEmpty()) {
                        jLabel.setText(textfield.getText());
                        setBackLabel(textfield, jLabel);
                    }
                }
            });
            setBackLabel(jLabel, textfield);
            evt.consume();
        }
    }//GEN-LAST:event_jLabelMouseClicked
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBClose;
    private javax.swing.JLabel jLabel;
    // End of variables declaration//GEN-END:variables
    private JTextField textfield;
    private JTabbedPane jTabbedPane;
    private UUID uniqueKey;
}
